name: TextEngine
description: Recursive pattern replacement engine for generating text from word and pattern lists.
version: 2.12.0
homepage: https://github.com/FarragoFiction/TextEngine
author: paradoxLands
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  test: any
