name: TextEngine
description: Recursive pattern replacement engine for generating text from word and pattern lists.
version: 1.24.2
homepage: https://github.com/FarragoFiction/TextEngine
author: paradoxLands

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  CommonLib:
    git:
      url: git://github.com/FarragoFiction/CommonLib.git
      ref: "Dart-1.24.2"
  LoaderLib:
    git:
      url: git://github.com/FarragoFiction/LoaderLib.git
      ref: "Dart-1.24.2"

dev_dependencies:
  test: ^0.12.0
